const patterns = [
    {
      id: "mushroom-duckling",
      name: "Mushroom Duckling",
      image: "images/projects/MushroomDuckling.jpeg",
      materials: ["Yarn: Himalaya Dolphin Baby: yelloy, red, white, pink, orange","4.0mm crochet hook","Toy stuffing","Scissors","Sewing pins","Yarn needle","18mm safety eyes",],
      abbreviations: ["mr – magic ring","sc – single crochet","dc – double crochet","ch – chain","inc – increase","dec – decrease","sl st – slip stitch","*n – repeat n times","rnd/rnds – round/rounds",],
      instructions: [
        "Mushroom (do not stuff) :",
        "1 rnd: with red: ch 2, crochet into the 2nd ch from the hook = 6",
        "2 rnd: (inc)*6 = 12",
        "3 rnd: (1 sc, inc)*6 = 18",
        "4 rnd: (2 sc, inc)*6 = 24",
        "5 rnd: (3 sc, inc)*6 = 30",
        "6 rnd: (4 sc, inc)*6 = 36",
        "7 rnd: (5 sc, inc)*6 = 42",
        "8 rnd: 3 sc, (inc 6 sc)*5, inc, 3 sc = 48",
        "9 rnd: 48 sc = 48",
        "10 ind: with white: in back loops only: 48 sc = 48",
        "11 rnd: (6 sc, dec)*6 = 42",
        "12 rnd: (5 sc, dec)*6 = 36",
        "13 rnd: (4 sc, dec)*6 = 30",
        "14 rnd: (3 sc, dec)*6 = 24",
        "15 rnd: (2 sc, dec)*6 = 18",
        "16-18 rnds: 18 sc (3 rnds) = 18",
        "Switch to yellow",
        "Body :",
        "1 rnd: in back loops only: (2 sc, inc)*6 = 24",
        "2 rnd: (3 sc, inc)*6 = 30",
        "3 rnd: (4 sc, inc)*6 = 36",
        "4-5 rnds: 36 sc (2 rnds) = 36",
        "6 rnd: (5 sc, inc)*6 = 42",
        "7 rnd: 42 sc = 42",
        "8 rnd: 5 sc, (inc, 3 sc)*3, 25 sc = 45",
        "9 rnd: 5 sc, (inc, 4 sc)*3, 25 sc = 48",
        "10-13 rnds: 48 sc (4 rnds) = 48",
        "Install safety eyes between rounds 7 and 8 at a distance of 7 sc",
        "14 rnd: (6 sc, dec)*6 = 42",
        "15 rnd: (5 sc, dec)*6 = 36",
        "16 rnd: (4 sc, dec)*6 = 30",
        "Gradually stuff the toy, starting from the top of the body. DO NOT stuff the mushroom hat",
        "17 rnd: (3 sc, dec)*6 = 24",
        "18 rnd: (2 sc, dec)*6 = 18",
        "19 rnd: (1 sc, dec)*6 = 12",
        "20 rnd: (dec)*6 = 6",
        "fasten off, close the opening",
        "Bill :",
        "1 rnd: with orange: ch 5, starting from the 2nd ch from the hook: (3 sc in 1 ch st, 2 sc)*2 = 10",
        "2 rnd: 10 sc = 10",
        "fasten off, leave and end for sewing",
        "Feet (x2) :",
        "1 rnd: with orange: ch 2, crochet into the 2nd ch from the hook: 6 sc = 6",
        "2 rnd: ch 2, 2 dc, ch 2, 2 sl st",
        "fasten off, leave and end for sewing",
        "Wings (x2) :",
        "1 rnd: with yellow: ch 2, crochet into the 2nd ch from the hook: 6 sc = 6",
        "2 rnd: (1 sc, inc)*3 = 9",
        "3-4 rnds: 9 sc = 9",
        "5 rnd: (1 sc, dec)*3 = 6",
        "fasten off, leave and end for sewing",
        "Sew to the body at rounds 8-9",
        "Sew the feet to the body between rounds 15 and 18. Embroider white spots all over the mushroom. Embroider cheeks between rounds 9-10."
      ]
    },
    {
      id: "pea-pod",
      name: "Peas in a Pod",
      image: "images/projects/PeaPod.jpeg",
      materials: ["Yarn size 6","5mm Hook","Saftey eyes","Scissors","Sewing needle","Stitch marker","Fiber fill",],
      abbreviations: ["mr – magic ring","sc – single crochet","inc – increase","dec – decrease","fo – fasten off",],
      instructions: [
        "Peas (x3) Light Green :",
        "1: 6 sc in MR = 6",
        "2: inc x 6 = 12",
        "3: 1 sc, 1 inc x 6 = 18",
        "4: 2 sc, 1 inc x 6 = 24",
        "5-7: 24 sc = 24",
        "8: 2 sc, 1 dec x 6 = 18",
        "9: 1 sc, 1 dec x 6 = 12",
        "10: dec x 6 = 6",
        "FO and sew shut, Hide tail after",
        "Place eyes between round 6 and 7, 4 visible stitches apart",
        "Pod (x2) Dark Green :",
        "Chain 1 and twist work at the end of each round",
        "1: Chain 26",
        "2: 25 sc (Start in second chain from hook) =25",
        "3-8: 25 sc = 25",
        "9: 1 inc, 23 sc, 1 inc = 27",
        "10: 1 inc, 25 sc, 1 inc = 29",
        "11: 1 inc, 27 sc, 1 inc = 31",
        "12: 31 sc = 31",
        "FO the first one (NOT the second one) and sc both along the sides together",
        "!Dont Sew The Opening For The Peas Shut!",
      ]
    },
    {
        id: "bee",
        name: "Bee",
        image: "images/projects/Bee.jpeg",
        materials: ["Yarn size 6","5mm Hook","Saftey eyes","Scissors","Sewing needle","Stitch marker","Fiber fill",],
        abbreviations: ["mr – magic ring","sc – single crochet","inc – increase","dec – decrease","fo – fasten off",],
        instructions: [
          "Body yellow :",
          "1: 6 sc in mr = 6",
          "2: 6 inc = 12",
          "3: (1 sc, 1 inc)*6 = 18",
          "4: (2 sc, 1 inc)*6 = 24",
          "5: (3 sc, 1 inc)*6 = 30",
          "6: (4 sc, 1 inc)*6 = 36",
          "7-9: sc around = 36",
          "10-12 brown: sc around = 36",
          "13-15 yellow: sc around = 36",
          "16-18 brown: sc around = 36",
          "19-20 yellow: sc around = 36",
          "21: (4 sc, 1 dec)*6 = 30",
          "22: (3 sc, 1 dec)*6 = 24",
          "23: (2 sc, 1 dec)*6 = 18",
          "24: (1 sc, 1 dec)*6 = 12",
          "25: 6 dec = 6",
          "FO",
          "Wings (x2) :",
          "1: 8 sc in mr = 8",
          "2: 8 inc = 16",
          "3: (1 sc, 1 inc)*8 = 24",
          "4: sc around = 24",
          "FO",
          "Place safety eyes between round 5-6"
        ]
      },
    {
        id: "duck",
        name: "Chunky Duck",
        image: "images/projects/Duck.jpeg",
        materials: ["Yarn: Himalaya dolphin","5mm Hook","Saftey eyes","Scissors","Sewing needle","Stitch marker","Fiber fill",],
        abbreviations: ["mr – magic ring","sc – single crochet","inc – increase","dec – decrease","st – stitch",],
        instructions: [
          "Body (start with green yarn) :",
          "1: 6 in mr = 6",
          "2: inc*6 = 12",
          "3: (1 sc, inc)*6 = 18",
          "4: (1 sc, 1 inc, 1 sc)*6 = 24",
          "5: (3 sc, 1 inc)*6 = 30",
          "6-8: sc around = 30",
          "9-10 white: sc around = 30",
          "11 brown: sc around = 30",
          "12: (2 sc, 1 inc, 2sc)*6 = 36",
          "13: (5 sc, 1 inc)*6 = 42",
          "14-17: sc around = 42",
          "18: (5 sc, 1 dec)*6 = 36",
          "19: (2 sc, 1 dec, 2 sc)*6 = 30",
          "20: (3 sc, 1 dec, 3 sc)*6 24",
          "21: (1 sc, 1 dec, 1 sc)*6 = 18",
          "Stuff the body and add safety eyes between rnd 6-7, 5-7 st apart",
          "22: (1 sc, 1dec)*6 = 12",
          "23: dec*6 = 6",
          "Fasten off and sew shut",
          "Arms and Legs :",
          "1: 4 sc in mr",
          "2: 4 sc",
          "Use brown yarn for the arms and yellow for the legs",
          "Assembly :",
          "Sew the arms between round 12-14",
          "Sew the legs between round 16-18",
          "Make teh mouth 1 row under the eyes in the middle"
        ]
      },
    // {
    //     id: "",
    //     name: "",
    //     image: "",
    //     materials: [""],
    //     abbreviations: [" – "],
    //     instructions: [
    //       ""
    //     ]
    //   },
  ];
